cmake_minimum_required(VERSION 3.10)

# Set the project name
project(ALSE_S2 LANGUAGES CXX)

# Add subdirectories
add_subdirectory("0. ejemplo_intro")
add_subdirectory("1. Ejemplo_Oper_Types")
add_subdirectory("2. Ejemplo_ControlStruc")
add_subdirectory("3. Ejemplos_funciones")
add_subdirectory("4. Punteros")
add_subdirectory("5. Clases")
#add_subdirectory(EjemploDoxygen)