cmake_minimum_required(VERSION 3.10)

# Set the project name
project(EjemploClases)

include_directories(include)


# Add the executable for ComplexUnified.cpp
#add_executable(ComplexUnified Complex.cpp)

# Add the executable for VehicleUnified.cpp 
#add_executable(VehicleUnified Vehicle.cpp)

# Add the executable for Cube.cpp
#add_executable(CubeSeparated src/Cube.cpp src/main.cpp)

# Add the executable for Complex.cpp
#add_executable(ComplexUnified src/Complex.cpp)

# Add the executable for Vehicle.cpp
#add_executable(VehicleUnified src/Vehicle.cpp)

# Add the library for Cube
add_library(Cube src/cube.cpp)
 
# Add the library for Complex
add_library(Complex src/complex.cpp)

# Add the library for Vehicle
add_library(Vehicle src/vehicle.cpp)
# Add the library for Car
add_library(Car src/car.cpp)
# Add the library for AirVehicle
add_library(AirVehicle src/air_vehicle.cpp)

add_library(vector src/vector2d.cpp)

# Add executable to use all classes
add_executable(AllClasses src/main.cpp)
target_link_libraries(AllClasses Cube Complex Vehicle Car AirVehicle) # Link the libraries to the executable

#add_executable(inheritance
#    src/Vehicle.cpp
#    src/Car.cpp
#    src/AirVehicle.cpp
#    src/mainInheritance.cpp
#)
add_executable(mainVector src/mainVector.cpp)# Add the executable for mainCube.cpp
target_link_libraries(mainVector vector)